# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme
- jekyll-titles-from-headings

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'Johannes Kloibhofer'
description: 'Personal webpage of Johannes Kloibhofer'
permalink: pretty
#logo: ""

# Basic Information 
title: Johannes Kloibhofer
position: PhD Candidate
department: ILLC
university: University of Amsterdam
email: j.kloibhofer@uva.nl

# Search Engine Optimization (SEO)
keywords: johannes kloibhofer, johannes, kloibhofer, jkloibhofer, j.kloibhofer, proof theory, modal logic, modal mu-calculus, cyclic proofs, mathematical logic, computational logic, non-wellfounded proofs, circular proofs
canonical: https://jkloibhofer.github.io/

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Research
  url: /research/
- title: Teaching
  url: /teaching/

#Plugin titles from headings
titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false

# Footer nav
navigation_footer:
- title: Back to home
  url: "#top"

